# Generated by Django 4.2.3 on 2023-07-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buttery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Батарея',
                'verbose_name_plural': 'Батареи',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Головной офис',
                'verbose_name_plural': 'Головные офисы',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель телефона')),
                ('dt', models.DateField(verbose_name='Дата выхода')),
                ('volume', models.ManyToManyField(related_name='phone', to='core.buttery', verbose_name='Заряд батареи')),
            ],
            options={
                'verbose_name': 'Смартфоны',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('dt', models.DateField(verbose_name='Дата создания компании')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.location', verbose_name='Головной офис')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.phone', verbose_name='Модель телефона')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
