# Generated by Django 4.2.3 on 2023-07-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='volume',
            new_name='buttery',
        ),
    ]
