# Generated by Django 4.2.3 on 2023-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_volume_phone_buttery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
    ]
