# Generated by Django 4.2.3 on 2023-07-25 12:30

from django.db import migrations


def add_country_to_location(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    countries = ['USA', 'South Korea', 'China']
    for country in countries:
        Location.objects.get_or_create(country=country)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_location_city'),
    ]

    operations = [
        migrations.RunPython(add_country_to_location),
    ]
